

services:

  server:
    build: ./server
    container_name: ally-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - AUTH_SERVICE_URL=http://auth-service:5002
      - DB_SERVICE_URL=http://db-service:5001
    depends_on:
      - auth-service
      - db-service

  auth-service:
    build: ./auth-service
    container_name: ally-auth-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_SERVICE_URL=http://db-service:5001
    depends_on:
      - db-service

  db-service:
    build: ./db-service
    container_name: ally-db-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001

  nginx:
    image: nginx:latest
    container_name: ally-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

