services:
  server:
    image: ally-server
    build: ./server
    ports:
      - "5000:5000"

  auth-service:
    image: ally-auth-service
    build: ./auth-service
    ports:
      - "5002:5002"

  db-service:
    image: ally-db-service
    build: ./db-service
    ports:
      - "5001:5001"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
